services:
  django:
    env_file: &env_file .env
    image: &image ${DOCKER_IMAGE}
    working_dir: &working_dir /opt/django    
    command:
      - gunicorn
      - config.wsgi
      - --bind
      - 0.0.0.0:8000
      - --log-level
      - info
    ports:
      - "8000:8000"    
    volumes:
      - /var/www/django/static:/opt/django/static
    depends_on: &depends_on
      - redis
    cpus: "0.1"
    mem_limit: 256m
    mem_reservation: 128m

  celery:
    env_file: *env_file
    image: *image
    working_dir: *working_dir    
    command:
      - uv
      - run
      - celery
      - --app=config
      - worker
      - --task-events
      - --concurrency=1
      - --loglevel=DEBUG    
    depends_on: *depends_on

  redis:
    image: redis:alpine
